apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'service']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 5m
      receiver: 'null'
      routes:
        - matchers:
            - alertname = "PaymentServiceHighErrorRate"
          receiver: korrelate-webhook
          group_wait: 10s
          group_interval: 30s
          repeat_interval: 5m
          continue: false

    receivers:
      - name: 'null'
      - name: korrelate-webhook
        webhook_configs:
          - url: 'http://172.20.0.1:8000/webhook'
            send_resolved: true
            http_config: {}
            max_alerts: 0
