apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: paymentservice-alerts
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: paymentservice.rules
      interval: 15s
      rules:
        - alert: PaymentServiceHighErrorRate
          expr: |
            (
              rate(paymentservice_requests_total{status_code="500"}[1m])
              /
              rate(paymentservice_requests_total[1m])
            ) > 0.20
          for: 1m
          labels:
            severity: critical
            service: paymentservice
          annotations:
            summary: "PaymentService error rate above 20%"
            description: "Error rate is {{ $value | humanizePercentage }}"
